### ISSUE TITLE
Check for std::cout, std::cerr and printf

### ISSUE THREAD

**Issue by dpiparo** [dpiparo/SAS#23]
Big software systems always come with an  advanced logging infrastructure. The usage of printouts may be considered an issue. This checker aims to identify this kind of printouts.

**Comment by zhengyangl** [comment]
https://github.com/zhengyangl/SAS/commit/ca0ba2dd3215cf5290ed4e6855e6b324278f39aa

**Comment by zhengyangl** [comment]
Hi, Danilo.
I've completed this checker. Please check :-)

**Comment by dpiparo** [comment]
I cannot but happily close the issue!
