### ISSUE TITLE
CMake should detect that clang is too old

### ISSUE THREAD

**Issue by Barthelemy** [dpiparo/SAS#36]
If clang 3.4 is installed the compilation fails. It should actually prevent CMake from finishing the configuration.

Looking at the CMakeLists.txt I think that FindClang.cmake is misused. It should not be "included" in my opinion. The cmake directory should be appended to the CMAKE_MODULE_PATH and then call `find_package(Clang 3.5 REQUIRED)`.

**Comment by dpiparo** [comment]
Closed since fixed by PR37
