### ISSUE TITLE
CMake configuration: add find llvm rather than specifying the directory by hand

### ISSUE THREAD

**Issue by dpiparo** [dpiparo/SAS#7]
Right now one specifies the llvm location with a CMake -D switch. This clearly needs improvement. The right way to go is to take advantage of a proper findLLVM CMake function. Many, many are already available, this ticket is meant to stress above all the need to integrate one of those.

**Comment by zhengyangl** [comment]
I'm trying it now:-)

**Comment by dpiparo** [comment]
Hi, I spoke too soon apparently. I just tried this on my kubuntu box and the configuration stopped with this message:
> -- The CXX compiler identification is GNU 4.9.2
> -- Check for working CXX compiler using: Ninja
> -- Check for working CXX compiler using: Ninja -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> CMake Error at cmake/FindLLVM.cmake:45 (MESSAGE):
>   Could NOT find LLVM
> Call Stack (most recent call first):
>   CMakeLists.txt:28 (INCLUDE)
> 
> -- Configuring incomplete, errors occurred!
> See also "XXX/build/CMakeFiles/CMakeOutput.log".

even if llvm is in this directory /usr/lib/llvm-3.5/
I reopened the issue.

**Comment by zhengyangl** [comment]
Hi sir
Sorry for the bug, but it works well on my box. I'll check it tomorrow. I'll test more before next commit

**Comment by dpiparo** [comment]
Hi Zhengyang, don't worry. This things happen. Out of curiosity, what platform are you working on?

**Comment by zhengyangl** [comment]
Ubuntu 14.04  with self-built LLVM/clang(SVN checkout). the prefix is default /usr/local.

**Comment by zhengyangl** [comment]
And two test boxes, with Ubuntu14.04 and FreeBSD10.1.

**Comment by dpiparo** [comment]
What I think would be the ideal solution is to preserve the switch and add the new automatic mechanism.
This way we can achieve something which is like before but better: if the cmake is not able to find llvm, the user can still use the variable (with the old name, LLVM_DEV_DIR) to point the build system to the right path.

**Comment by zhengyangl** [comment]
Hi, Danilo
The FindLLVM.cmake script is based on llvm-config. If cmake cannot find llvm-config in $PATH, it will report "Cannot find LLVM". It seems that this is a reasonable way of finding LLVM.  Could you check  llvm-config on your platform?

**Comment by dpiparo** [comment]
Hi,

I just checked: it works flawlessly. Thanks.

Danilo
